[project]
name = "text-summary"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "evaluate>=0.4.5",
    "nltk>=3.9.1",
    "transformers[torch]>=4.54.1",
]
